# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14E3YImV11sF33-aClAWD9xczEmT3qr4M
"""

# ==========================================================
# Climate Resilience Dashboard
# Configuration
# ==========================================================

# ----------------------------------------------------------
# Dashboard
# ----------------------------------------------------------

APP_TITLE = "Climate Resilience vs Economic Growth"

APP_ICON = "🌍"

DEFAULT_YEAR = 2023

# ----------------------------------------------------------
# Color Palette (CVD-safe)
# ----------------------------------------------------------

PRIMARY = "#2C7FB8"

SUCCESS = "#2E8B57"

WARNING = "#E69F00"

DANGER = "#D55E00"

GREY = "#B0B0B0"

BACKGROUND = "#FFFFFF"

# ----------------------------------------------------------
# Plotly
# ----------------------------------------------------------

PLOT_TEMPLATE = "plotly_white"