# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8wZVkibhlL9qpSQSU8YTlx4sAZzpPLN
"""

# ==========================================================
# Climate Resilience Dashboard
# Main Application
# ==========================================================

import streamlit as st

from config import APP_ICON, APP_TITLE

# ----------------------------------------------------------
# Page Configuration
# ----------------------------------------------------------

st.set_page_config(
    page_title=APP_TITLE,
    page_icon=APP_ICON,
    layout="wide",
    initial_sidebar_state="expanded"
)

# ----------------------------------------------------------
# Sidebar
# ----------------------------------------------------------

#with st.sidebar:
 #   st.caption("👉 Use the menu below to explore the dashboard.")
  #  st.divider()
    # NOTE: once pages/ folder is created, Streamlit auto-populates
    # nav links here. No manual nav code needed for that part.

# ----------------------------------------------------------
# Home
# ----------------------------------------------------------

st.markdown(
    """
    <div style="max-width: 900px; margin: 0 auto;">
    """,
    unsafe_allow_html=True
)

st.title("🌍 Beyond Economic Growth")
st.subheader("Why Climate Resilience Matters as Much as GDP")

st.markdown(
    """
    <div style="
        border-left: 4px solid #2A6F97;
        padding: 8px 20px;
        margin: 20px 0 16px 0;
        font-size: 1.25rem;
        font-style: italic;
        color: #2A6F97;
    ">
    Economic growth is often assumed to guarantee better living standards —
    but does it guarantee food security?
    </div>
    """,
    unsafe_allow_html=True
)

st.markdown(
    """
    <div style="font-size: 1.05rem; color: #333; line-height: 1.6; margin-bottom: 32px;">
    This interactive dashboard tests that assumption — examining whether climate
    stress and agricultural capacity shape food availability as much as economic
    development does, across 178 countries from 2010 to 2023, using FAOSTAT and
    World Bank data.
    </div>
    """,
    unsafe_allow_html=True
)
col1, col2, col3, col4 = st.columns(4)
stats = [
    ("🌍", "COUNTRIES", "178"),
    ("📅", "YEARS COVERED", "2010–2023"),
    ("🗂️", "DATASETS MERGED", "5"),
    ("📊", "DASHBOARD VIEWS", "7"),
]
for col, (icon, label, value) in zip([col1, col2, col3, col4], stats):
    with col:
        st.markdown(
            f"""
            <div style="
                background-color: #FFFFFF;
                border-radius: 10px;
                box-shadow: 0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08);
                padding: 16px 18px;
                min-height: 95px;
                display: flex;
                flex-direction: column;
                justify-content: center;
            ">
                <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
                    <span style="font-size: 1.4rem;">{icon}</span>
                    <span style="color: #666; font-size: 1rem; font-weight: 700;
                                 letter-spacing: 0.04em;">{label}</span>
                </div>
                <div style="font-size: 1.9rem; font-weight: 800; color: #14213d;">{value}</div>
            </div>
            """,
            unsafe_allow_html=True
        )

st.markdown("</div>", unsafe_allow_html=True)