# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVv891jV_OdgIHwnSNMRnoVNzYCPewh-
"""

# ==========================================================
# utils.py — Shared data loading & filters for all dashboard pages
# ==========================================================
from pathlib import Path
import pandas as pd
import streamlit as st

@st.cache_data(show_spinner=False)
def load_data():
    """
    Load the processed Country-Year KPI dataset.
    One row per Country-Year; item-level detail already aggregated
    in Notebook 2 (Phase 11), filtered to Item == "Grand Total".
    """
    data_path = Path("data/processed/KPI_Country_Year_Dataset.csv")
    return pd.read_csv(data_path)


def apply_sidebar_filters(df):
    """
    Shared sidebar controls: Year range + Region.
    Returns the filtered dataframe. Call this at the top of every page
    so Year/Region behave identically across the whole dashboard.
    """
    #st.sidebar.caption("👉 Use the menu below to explore the dashboard.")
    #st.sidebar.divider()

    st.sidebar.subheader("Filters")

    year_min, year_max = int(df["Year"].min()), int(df["Year"].max())
    year_range = st.sidebar.slider(
        "Year", year_min, year_max, (year_min, year_max)
    )

    all_regions = sorted(df["Region"].dropna().unique())
    selected_regions = st.sidebar.multiselect(
        "Region", options=all_regions, default=all_regions
    )

    if st.sidebar.button("Reset Filters"):
        st.rerun()

    filtered = df[
        (df["Year"] >= year_range[0]) &
        (df["Year"] <= year_range[1]) &
        (df["Region"].isin(selected_regions))
    ]

    return filtered, year_range, selected_regions


DISPLAY_NAME_OVERRIDES = {
    "Yemen, Rep.": "Yemen",
    "Egypt, Arab Rep.": "Egypt",
    "Iran, Islamic Rep.": "Iran",
    "Venezuela, RB": "Venezuela",
    "Korea, Rep.": "South Korea",
    "Korea, Dem. People's Rep.": "North Korea",
    "Congo, Dem. Rep.": "DR Congo",
    "Congo, Rep.": "Congo",
    "Lao PDR": "Laos",
    "Bahamas, The": "The Bahamas",
    "Gambia, The": "The Gambia",
}

def clean_name(country):
    """
    Cosmetic display-name cleanup for prose/labels (insight cards,
    dropdowns, rankings). Do NOT use this for the choropleth map —
    Plotly's locationmode="country names" needs the original
    World Bank spelling to match correctly.
    """
    return DISPLAY_NAME_OVERRIDES.get(country, country)