# -*- coding: utf-8 -*-
"""0_📊_Executive_Overview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xmTJjIKvdM_ibdjaQ8onKO-ZBd-ylU1
"""

# ==========================================================
# Executive Overview
# ==========================================================
import streamlit as st
import plotly.express as px

from utils import load_data, apply_sidebar_filters, clean_name

st.set_page_config(page_title="Executive Overview", page_icon="📊", layout="wide")

df = load_data()
filtered_df, year_range, selected_regions = apply_sidebar_filters(df)

st.title("📊 Executive Overview")
st.subheader("The State of Food Security, By the Numbers")

latest_year = year_range[1]
latest_df = filtered_df[filtered_df["Year"] == latest_year]

avg_calories = latest_df["Calories_per_Capita"].mean()
avg_gdp = latest_df["GDP_per_Capita"].mean()
avg_temp = latest_df["Temperature_Change"].mean()
n_countries = latest_df["Country"].nunique()

st.caption(f"Snapshot as of {latest_year} · {n_countries} countries in current filter")

# ----------------------------------------------------------
# KPI Row
# ----------------------------------------------------------
col1, col2, col3, col4 = st.columns(4)
kpis = [
    ("🍽️", "AVG. CALORIE SUPPLY", f"{avg_calories:,.0f} kcal/day"),
    ("💰", "AVG. GDP PER CAPITA", f"${avg_gdp:,.0f}"),
    ("🌡️", "AVG. TEMP. ANOMALY", f"+{avg_temp:.2f}°C"),
    ("🗺️", "COUNTRIES SHOWN", f"{n_countries}"),
]
for col, (icon, label, value) in zip([col1, col2, col3, col4], kpis):
    with col:
        st.markdown(
            f"""
            <div style="
                background-color:#FFFFFF; border-radius:10px;
                box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08);
                padding:16px 18px; min-height:95px;
                display:flex; flex-direction:column; justify-content:center;">
                <div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;">
                    <span style="font-size:1.4rem;">{icon}</span>
                    <span style="color:#666; font-size:0.95rem; font-weight:700;
                                 letter-spacing:0.03em;">{label}</span>
                </div>
                <div style="font-size:1.6rem; font-weight:800; color:#14213d;">{value}</div>
            </div>
            """,
            unsafe_allow_html=True
        )

st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# World Map
# ----------------------------------------------------------
st.markdown("#### Where Does Food Security Stand Today?")
st.markdown(
    f"""
    <div style="font-size:1rem; color:#555; margin-bottom:12px; line-height:1.5;">
    Darker blue indicates higher average daily calorie availability per person
    in {latest_year}; grey indicates lower availability. Hover over a country for details.
    </div>
    """,
    unsafe_allow_html=True
)

fig_map = px.choropleth(
    latest_df,
    locations="Country",
    locationmode="country names",
    color="Calories_per_Capita",
    hover_name="Country",
    hover_data={"GDP_per_Capita": ":,.0f", "Temperature_Change": ":.2f"},
    color_continuous_scale=["#B0B0B0", "#2A6F97"],
    labels={"Calories_per_Capita": "Calories/Capita"},
)
fig_map.update_layout(
    margin=dict(l=0, r=0, t=10, b=0),
    coloraxis_colorbar=dict(title="Calories<br>per Capita"),
    geo=dict(showframe=False, showcoastlines=False, projection_type="natural earth"),
)
st.plotly_chart(fig_map, use_container_width=True)

st.markdown("<div style='margin-top:36px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Three Key Insights
# ----------------------------------------------------------
st.markdown("#### Three Key Insights")

richest = latest_df.loc[latest_df["GDP_per_Capita"].idxmax()]
warmest = latest_df.loc[latest_df["Temperature_Change"].idxmax()]
lowest_cal = latest_df.loc[latest_df["Calories_per_Capita"].idxmin()]

def insight_card(bg, border, text_html):
    st.markdown(
        f"""
        <div style="
            background-color:{bg};
            border-left:4px solid {border};
            box-shadow:0 4px 14px rgba(0,0,0,0.08), 0 1px 3px rgba(0,0,0,0.06);
            padding:16px 18px;
            border-radius:8px;
            height:130px;
            display:flex;
            align-items:center;
            color:#262730;
            font-size:1.05rem;
            line-height:1.55;
        ">
        <div>{text_html}</div>
        </div>
        """,
        unsafe_allow_html=True
    )

i1, i2, i3 = st.columns(3)
with i1:
    insight_card(
        "rgba(42,111,151,0.08)", "#2A6F97",
        f"<b>{clean_name(richest['Country'])}</b> leads in GDP per capita "
        f"(${richest['GDP_per_Capita']:,.0f}), but that alone doesn't guarantee "
        f"the highest food security."
    )
with i2:
    insight_card(
        "rgba(224,122,44,0.08)", "#E07A2C",
        f"<b>{clean_name(warmest['Country'])}</b> shows the steepest warming trend "
        f"(+{warmest['Temperature_Change']:.2f}°C), a key climate-stress signal."
    )
with i3:
    insight_card(
        "rgba(176,176,176,0.18)", "#8a8a8a",
        f"<b>{clean_name(lowest_cal['Country'])}</b> has the lowest calorie availability in "
        f"this view ({lowest_cal['Calories_per_Capita']:.0f} kcal/day) — a food "
        f"security risk point."
    )

st.markdown("<div style='margin-top:48px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Closing Thesis Section
# ----------------------------------------------------------
st.markdown("#### The Question Behind This Dashboard")

st.markdown(
    """
    <div style="
        border-left: 4px solid #2A6F97;
        padding: 10px 20px;
        margin: 16px 0 16px 0;
        font-size: 1.2rem;
        font-style: italic;
        color: #2A6F97;
    ">
    Does economic growth guarantee food security — or does climate stress matter just as much?
    </div>
    """,
    unsafe_allow_html=True
)

st.markdown(
    """
    <div style="font-size:1.05rem; color:#333; line-height:1.6; max-width:900px;">
    This dashboard follows that question through global trends, individual countries,
    and a composite resilience ranking, using FAOSTAT and World Bank data across
    178 countries from 2010 to 2023.
    </div>
    """,
    unsafe_allow_html=True
)