# -*- coding: utf-8 -*-
"""1_🌍_Global_Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewVQ3QKjWRqsZ35Gw30k5asYtjaGrpw6
"""

# ==========================================================
# Global Trends (AQ11)
# ==========================================================
import streamlit as st
import pandas as pd
from plotly.subplots import make_subplots
import plotly.graph_objects as go

from utils import load_data, apply_sidebar_filters

st.set_page_config(page_title="Global Trends", page_icon="🌍", layout="wide")

df = load_data()
filtered_df, year_range, selected_regions = apply_sidebar_filters(df)

st.title("🌍 Global Trends")
st.subheader("Two Trajectories: Global Food Supply and a Warming Planet")

# ----------------------------------------------------------
# Global aggregate by year
# ----------------------------------------------------------
global_trend = (
    filtered_df.groupby("Year", as_index=False)
    .agg({"Calories_per_Capita": "mean", "Temperature_Change": "mean"})
    .sort_values("Year")
)

base_year = global_trend["Year"].min()
base_cal = global_trend.loc[global_trend["Year"] == base_year, "Calories_per_Capita"].values[0]
base_temp = global_trend.loc[global_trend["Year"] == base_year, "Temperature_Change"].values[0]

# Food supply: safe to express as % change (values are large, far from zero)
global_trend["Calorie_Pct_Change"] = ((global_trend["Calories_per_Capita"] / base_cal) - 1) * 100
# Temperature: NOT indexed as a percentage — anomaly values sit near zero, so a
# percentage index would exaggerate small fluctuations. Shown instead as the
# actual °C change from the base year, which is directly interpretable.
global_trend["Temp_Delta_C"] = global_trend["Temperature_Change"] - base_temp

st.markdown(
    f"""
    <div style="font-size:1rem; color:#555; margin-bottom:16px; line-height:1.5;">
    Food supply is shown as <b>% change from {base_year}</b>; temperature anomaly is shown
    as <b>°C change from {base_year}</b> — kept on separate panels rather than one shared
    scale, since forcing near-zero temperature values into a percentage index would
    exaggerate small year-to-year swings.
    </div>
    """,
    unsafe_allow_html=True
)

view = st.radio(
    "View", ["Global Aggregate", "By Region"], horizontal=True, label_visibility="collapsed"
)

if view == "Global Aggregate":
    fig = make_subplots(
        rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.08,
        subplot_titles=(
            f"Food Supply — % Change from {base_year}",
            f"Temperature Anomaly — °C Change from {base_year}",
        ),
    )

    fig.add_trace(go.Scatter(
        x=global_trend["Year"], y=global_trend["Calorie_Pct_Change"],
        mode="lines+markers", line=dict(color="#2A6F97", width=3), marker=dict(size=6),
        showlegend=False,
    ), row=1, col=1)

    fig.add_trace(go.Scatter(
        x=global_trend["Year"], y=global_trend["Temp_Delta_C"],
        mode="lines+markers", line=dict(color="#E07A2C", width=3), marker=dict(size=6),
        fill="tozeroy", fillcolor="rgba(224,122,44,0.08)",
        showlegend=False,
    ), row=2, col=1)

    fig.add_hline(y=0, line_dash="dot", line_color="#B0B0B0", row=1, col=1)
    fig.add_hline(y=0, line_dash="dot", line_color="#B0B0B0", row=2, col=1)

    fig.update_yaxes(title_text="% change", gridcolor="#eee", row=1, col=1)
    fig.update_yaxes(title_text="°C change", gridcolor="#eee", row=2, col=1)
    fig.update_xaxes(showgrid=False, dtick=1, row=2, col=1)
    fig.update_layout(
        height=560, margin=dict(l=0, r=20, t=40, b=0),
        plot_bgcolor="white", font=dict(size=13),
    )
    fig.update_annotations(font_size=14)
    st.plotly_chart(fig, use_container_width=True)
    st.caption(
        "Source: FAOSTAT Food Balance Sheets & Temperature Change on Land. "
        f"Global average across {filtered_df['Country'].nunique()} countries in current filter."
    )

else:
    region_trend = (
        filtered_df.groupby(["Year", "Region"], as_index=False)
        .agg({"Calories_per_Capita": "mean"})
    )
    region_base = region_trend[region_trend["Year"] == base_year].set_index("Region")["Calories_per_Capita"]
    region_trend["Calorie_Pct_Change"] = region_trend.apply(
        lambda r: ((r["Calories_per_Capita"] / region_base.get(r["Region"], r["Calories_per_Capita"])) - 1) * 100,
        axis=1
    )

    region_colors = {
        "Africa": "#E07A2C", "Asia": "#2A6F97", "Europe": "#5B9BD5",
        "Americas": "#B0B0B0", "Oceania": "#70AD47",
    }

    fig2 = go.Figure()
    for region, color in region_colors.items():
        rdf = region_trend[region_trend["Region"] == region]
        if rdf.empty:
            continue
        fig2.add_trace(go.Scatter(
            x=rdf["Year"], y=rdf["Calorie_Pct_Change"],
            mode="lines", name=region, line=dict(color=color, width=2.5),
        ))

    fig2.add_hline(y=0, line_dash="dot", line_color="#ccc")
    fig2.update_layout(
        margin=dict(l=0, r=0, t=10, b=0),
        plot_bgcolor="white",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        xaxis=dict(showgrid=False, dtick=1),
        yaxis=dict(title=f"Food Supply — % Change from {base_year}", gridcolor="#eee"),
        font=dict(size=13),
    )
    st.plotly_chart(fig2, use_container_width=True)
    st.caption(
        f"Source: FAOSTAT Food Balance Sheets. Regional food supply, "
        f"% change from {base_year}."
    )

st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Key takeaway — states the actual comparison honestly
# ----------------------------------------------------------
cal_change = global_trend["Calorie_Pct_Change"].iloc[-1]
temp_delta = global_trend["Temp_Delta_C"].iloc[-1]
latest_yr = int(global_trend["Year"].iloc[-1])

st.markdown(
    f"""
    <div style="
        border-left: 4px solid #2A6F97;
        background-color: rgba(42,111,151,0.06);
        padding: 14px 20px;
        border-radius: 6px;
        font-size: 1.05rem;
        color: #262730;
        line-height: 1.6;
    ">
    Between <b>{base_year}</b> and <b>{latest_yr}</b>, global average calorie supply
    grew by just <b>{cal_change:+.1f}%</b>, while the average temperature anomaly rose
    by <b>{temp_delta:+.2f}°C</b> — a much sharper shift in relative terms. Food supply
    has grown steadily, but climate stress is accelerating far faster than food
    systems have adapted.
    </div>
    """,
    unsafe_allow_html=True
)