# -*- coding: utf-8 -*-
"""5_🔎_Country_Explorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHyNMtGAJgKM7b8JIUx0DAnQc6WdLJNP
"""

# ==========================================================
# Country Explorer
# ==========================================================
import streamlit as st
import numpy as np
import pandas as pd
from plotly.subplots import make_subplots
import plotly.graph_objects as go

from utils import load_data, apply_sidebar_filters, clean_name

st.set_page_config(page_title="Country Explorer", page_icon="🔎", layout="wide")

df = load_data()
filtered_df, year_range, selected_regions = apply_sidebar_filters(df)

st.title("🔎 Country Explorer")
st.subheader("Pick Any Country. See Its Full Story.")

st.markdown(
    '<div style="font-size:1.05rem; color:#333; line-height:1.6; max-width:900px; margin-bottom:20px;">'
    "Every chart so far has looked at all countries at once. Here, follow a single country's "
    "trajectory across economy, climate, agriculture, and trade — measured against its regional "
    "peers, not just against itself."
    "</div>",
    unsafe_allow_html=True
)

available_countries = sorted(filtered_df["Country"].unique(), key=lambda c: clean_name(c))
country_display_map = {clean_name(c): c for c in available_countries}
display_names = sorted(country_display_map.keys())

default_index = display_names.index("Germany") if "Germany" in display_names else 0

selected_display = st.selectbox("Choose a country:", display_names, index=default_index)
selected_country = country_display_map[selected_display]

country_df = filtered_df[filtered_df["Country"] == selected_country].sort_values("Year").copy()

if country_df.empty:
    st.warning("No data available for this country in the current filter selection.")
    st.stop()

country_df["Net_Trade"] = country_df["Exports_Total"] - country_df["Imports_Total"]

country_region = country_df["Region"].iloc[0]
region_df = filtered_df[filtered_df["Region"] == country_region].copy()
region_df["Net_Trade"] = region_df["Exports_Total"] - region_df["Imports_Total"]

region_avg = (
    region_df.groupby("Year", as_index=False)
    .agg({
        "GDP_per_Capita": "mean",
        "Calories_per_Capita": "mean",
        "Temperature_Change": "mean",
        "Agricultural_Land_Percent": "mean",
        "Production_Total": "mean",
        "Net_Trade": "mean",
    })
)

latest_year = country_df["Year"].max()
latest_row = country_df[country_df["Year"] == latest_year].iloc[0]
region_latest = region_avg[region_avg["Year"] == latest_year].iloc[0]

st.markdown(
    f'<div style="font-size:0.95rem; color:#666; margin-bottom:16px;">'
    f"Showing <b>{clean_name(selected_country)}</b> ({country_region}) vs. the "
    f"<b>{country_region}</b> regional average · {int(country_df['Year'].min())}–{int(latest_year)}"
    f"</div>",
    unsafe_allow_html=True
)

# ----------------------------------------------------------
# KPI row
# ----------------------------------------------------------
def kpi_card(label, country_val, region_val, fmt="{:,.0f}", higher_is_better=True):
    delta = country_val - region_val
    pct_delta = (delta / region_val * 100) if region_val else 0
    is_above = delta >= 0
    good = is_above if higher_is_better else not is_above
    delta_color = "#2A6F97" if good else "#E07A2C"
    arrow = "▲" if is_above else "▼"
    return f"""
    <div style="background-color:#FFFFFF; border-radius:10px;
        box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08);
        padding:14px 16px; min-height:100px; display:flex; flex-direction:column; justify-content:center;">
        <div style="color:#666; font-size:0.82rem; font-weight:700; letter-spacing:0.03em; margin-bottom:6px;">{label}</div>
        <div style="font-size:1.5rem; font-weight:800; color:#14213d;">{fmt.format(country_val)}</div>
        <div style="font-size:0.8rem; color:{delta_color}; font-weight:600; margin-top:2px;">
            {arrow} {abs(pct_delta):.0f}% vs. region
        </div>
    </div>
    """

k1, k2, k3, k4 = st.columns(4)
with k1:
    st.markdown(kpi_card("GDP PER CAPITA", latest_row["GDP_per_Capita"], region_latest["GDP_per_Capita"], "${:,.0f}"), unsafe_allow_html=True)
with k2:
    st.markdown(kpi_card("CALORIE SUPPLY", latest_row["Calories_per_Capita"], region_latest["Calories_per_Capita"], "{:,.0f} kcal"), unsafe_allow_html=True)
with k3:
    st.markdown(kpi_card("TEMP. ANOMALY", latest_row["Temperature_Change"], region_latest["Temperature_Change"], "+{:.2f}°C", higher_is_better=False), unsafe_allow_html=True)
with k4:
    st.markdown(kpi_card("AGRICULTURAL LAND", latest_row["Agricultural_Land_Percent"], region_latest["Agricultural_Land_Percent"], "{:.0f}%"), unsafe_allow_html=True)

st.markdown("<div style='margin-top:40px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Six synchronized small multiples
# ----------------------------------------------------------
st.markdown("#### The Full Trajectory, Side by Side")
st.markdown(
    '<div style="font-size:1rem; color:#555; margin-bottom:12px; line-height:1.5;">'
    f'<span style="color:#2A6F97; font-weight:600;">■ {clean_name(selected_country)}</span> &nbsp; vs. &nbsp; '
    f'<span style="color:#B0B0B0; font-weight:600;">■ {country_region} average</span>'
    "</div>",
    unsafe_allow_html=True
)

metrics = [
    ("GDP_per_Capita", "GDP per Capita (USD)"),
    ("Calories_per_Capita", "Calorie Supply (kcal/day)"),
    ("Temperature_Change", "Temperature Anomaly (°C)"),
    ("Agricultural_Land_Percent", "Agricultural Land (% of area)"),
    ("Production_Total", "Domestic Production (tonnes)"),
    ("Net_Trade", "Net Trade — Exports minus Imports (tonnes)"),
]

fig = make_subplots(
    rows=2, cols=3,
    subplot_titles=[m[1] for m in metrics],
    vertical_spacing=0.20, horizontal_spacing=0.07,
)

positions = [(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3)]

for (col_name, title), (r, c) in zip(metrics, positions):
    fig.add_trace(go.Scatter(
        x=region_avg["Year"], y=region_avg[col_name],
        mode="lines", line=dict(color="#B0B0B0", width=2, dash="dot"),
        showlegend=False, hoverinfo="skip",
    ), row=r, col=c)

    fig.add_trace(go.Scatter(
        x=country_df["Year"], y=country_df[col_name],
        mode="lines+markers", line=dict(color="#2A6F97", width=2.5), marker=dict(size=4),
        showlegend=False,
        hovertemplate=f"%{{x}}<br>{title}: %{{y:,.1f}}<extra></extra>",
    ), row=r, col=c)

    if col_name == "Net_Trade":
        fig.add_hline(y=0, line_dash="dot", line_color="#ddd", row=r, col=c)

    fig.update_xaxes(showgrid=False, dtick=4, row=r, col=c, tickfont=dict(size=9))
    fig.update_yaxes(gridcolor="#f0f0f0", tickfont=dict(size=9), row=r, col=c)

fig.update_layout(
    height=580,
    margin=dict(l=10, r=10, t=50, b=10),
    plot_bgcolor="white",
    font=dict(size=12),
)
fig.update_annotations(font_size=12, font_color="#333")

st.plotly_chart(fig, use_container_width=True)
st.caption(
    "Source: FAOSTAT & World Bank, merged panel. Dotted grey line is the regional average "
    f"across all {country_region} countries in the current filter; solid blue is {clean_name(selected_country)}. "
    "Net Trade above zero means the country exports more than it imports."
)

st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Dynamic takeaway — now correctly detects "diminishing returns"
# ----------------------------------------------------------
gdp_gap = ((latest_row["GDP_per_Capita"] - region_latest["GDP_per_Capita"]) / region_latest["GDP_per_Capita"]) * 100
cal_gap = ((latest_row["Calories_per_Capita"] - region_latest["Calories_per_Capita"]) / region_latest["Calories_per_Capita"]) * 100

if gdp_gap > 0 and cal_gap > 0 and gdp_gap > 3 * max(cal_gap, 1):
    story = (f"{clean_name(selected_country)}'s GDP sits <b>{gdp_gap:+.0f}%</b> above the {country_region} "
              f"average, but calorie supply is only <b>{cal_gap:+.0f}%</b> above average — a clear case of "
              f"diminishing returns. Beyond a certain point, extra wealth buys very little extra food security.")
elif gdp_gap > 10 and cal_gap < -5:
    story = (f"{clean_name(selected_country)} sits well above the {country_region} average on GDP "
              f"({gdp_gap:+.0f}%) but below average on calorie supply ({cal_gap:+.0f}%) — a case where "
              f"wealth hasn't translated into food security at all.")
elif gdp_gap < -10 and cal_gap > 5:
    story = (f"{clean_name(selected_country)} sits below the {country_region} average on GDP "
              f"({gdp_gap:+.0f}%) yet above average on calorie supply ({cal_gap:+.0f}%) — a case of "
              f"food security achieved without high income.")
else:
    story = (f"{clean_name(selected_country)}'s GDP ({gdp_gap:+.0f}% vs. regional average) and calorie "
              f"supply ({cal_gap:+.0f}% vs. regional average) move roughly proportionally — no major "
              f"disconnect between wealth and food security here.")

st.markdown(
    f'<div style="border-left:4px solid #2A6F97; background-color:rgba(42,111,151,0.06); '
    f'padding:14px 20px; border-radius:6px; font-size:1.05rem; color:#262730; line-height:1.6;">'
    f"{story}"
    f'</div>',
    unsafe_allow_html=True
)