# -*- coding: utf-8 -*-
"""2_💰_Economy_&_Food.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13--5rwK4ql5Z1-oKZrtzc-R7bCtxSgli
"""

# ==========================================================
# Economy & Food (AQ1)
# ==========================================================
import streamlit as st
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from utils import load_data, apply_sidebar_filters, clean_name

st.set_page_config(page_title="Economy & Food", page_icon="💰", layout="wide")

df = load_data()
filtered_df, year_range, selected_regions = apply_sidebar_filters(df)

st.title("💰 Economy & Food")
st.subheader("More Wealth Doesn't Always Mean More Food")

latest_year = year_range[1]
year_df = filtered_df[filtered_df["Year"] == latest_year].dropna(
    subset=["GDP_per_Capita", "Calories_per_Capita"]
).copy()

st.caption(
    f"Cross-section for {latest_year} · {year_df['Country'].nunique()} countries in current filter"
)

# ----------------------------------------------------------
# Correlation + R² KPIs
# ----------------------------------------------------------
log_gdp = np.log10(year_df["GDP_per_Capita"])
corr = np.corrcoef(log_gdp, year_df["Calories_per_Capita"])[0, 1]
r_squared = corr ** 2

col1, col2, col3 = st.columns([1, 1, 2])
with col1:
    st.markdown(
        f"""
        <div style="
            background-color:#FFFFFF; border-radius:10px;
            box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08);
            padding:16px 18px; min-height:95px;
            display:flex; flex-direction:column; justify-content:center;">
            <div style="color:#666; font-size:0.95rem; font-weight:700;
                        letter-spacing:0.03em; margin-bottom:8px;">CORRELATION</div>
            <div style="font-size:1.9rem; font-weight:800; color:#14213d;">{corr:.2f}</div>
        </div>
        """,
        unsafe_allow_html=True
    )
with col2:
    st.markdown(
        f"""
        <div style="
            background-color:#FFFFFF; border-radius:10px;
            box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08);
            padding:16px 18px; min-height:95px;
            display:flex; flex-direction:column; justify-content:center;">
            <div style="color:#666; font-size:0.95rem; font-weight:700;
                        letter-spacing:0.03em; margin-bottom:8px;">GDP EXPLAINS</div>
            <div style="font-size:1.9rem; font-weight:800; color:#14213d;">{r_squared*100:.0f}%</div>
        </div>
        """,
        unsafe_allow_html=True
    )
with col3:
    st.markdown(
        f"""
        <div style="font-size:1.05rem; color:#333; line-height:1.6; padding-top:12px;">
        GDP explains roughly <b>{r_squared*100:.0f}%</b> of the difference in food
        availability across countries. The remaining <b>{100-r_squared*100:.0f}%</b>
        comes from other forces — climate stress, agricultural capacity, and trade —
        which the rest of this dashboard explores.
        </div>
        """,
        unsafe_allow_html=True
    )

st.markdown("<div style='margin-top:28px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Main Scatter: GDP vs Food Availability
# ----------------------------------------------------------
st.markdown("#### Does GDP Per Capita Predict Food Availability?")
st.markdown(
    """
    <div style="font-size:1rem; color:#555; margin-bottom:8px; line-height:1.5;">
    Each point is one country. GDP is shown on a logarithmic scale since income spans
    a very wide range across countries.
    </div>
    """,
    unsafe_allow_html=True
)

slope, intercept = np.polyfit(log_gdp, year_df["Calories_per_Capita"], 1)
trend_x = np.linspace(log_gdp.min(), log_gdp.max(), 100)
trend_y = slope * trend_x + intercept

fig = px.scatter(
    year_df,
    x="GDP_per_Capita",
    y="Calories_per_Capita",
    hover_name="Country",
    log_x=True,
    color_discrete_sequence=["#2A6F97"],
    labels={
        "GDP_per_Capita": "GDP per Capita (USD, log scale)",
        "Calories_per_Capita": "Calorie Supply (kcal/capita/day)",
    },
    opacity=0.55,
)
fig.update_traces(marker=dict(size=8, line=dict(width=0.5, color="white")))

fig.add_trace(go.Scatter(
    x=10 ** trend_x, y=trend_y,
    mode="lines", name="Trend",
    line=dict(color="#888", width=2, dash="dash"),
    showlegend=False, hoverinfo="skip",
))

year_df["predicted"] = slope * log_gdp + intercept
year_df["residual"] = year_df["Calories_per_Capita"] - year_df["predicted"]

top_over = year_df.loc[year_df["residual"].idxmax()]
top_under = year_df.loc[year_df["residual"].idxmin()]

fig.add_trace(go.Scatter(
    x=[top_over["GDP_per_Capita"]], y=[top_over["Calories_per_Capita"]],
    mode="markers", marker=dict(size=13, color="#2A6F97", line=dict(width=2, color="white")),
    showlegend=False, hoverinfo="skip",
))
fig.add_annotation(
    x=np.log10(top_over["GDP_per_Capita"]), y=top_over["Calories_per_Capita"],
    xref="x", yref="y",
    text=f"<b>{clean_name(top_over['Country'])}</b><br>food-secure well above its GDP level",
    showarrow=True, arrowhead=2, arrowwidth=1.5, arrowcolor="#2A6F97",
    ax=60, ay=-40, font=dict(size=12, color="#2A6F97"),
    bgcolor="rgba(255,255,255,0.9)", bordercolor="#2A6F97", borderwidth=1, borderpad=4,
)

fig.add_trace(go.Scatter(
    x=[top_under["GDP_per_Capita"]], y=[top_under["Calories_per_Capita"]],
    mode="markers", marker=dict(size=13, color="#E07A2C", line=dict(width=2, color="white")),
    showlegend=False, hoverinfo="skip",
))
fig.add_annotation(
    x=np.log10(top_under["GDP_per_Capita"]), y=top_under["Calories_per_Capita"],
    xref="x", yref="y",
    text=f"<b>{clean_name(top_under['Country'])}</b><br>food-insecure despite its GDP level",
    showarrow=True, arrowhead=2, arrowwidth=1.5, arrowcolor="#E07A2C",
    ax=-60, ay=40, font=dict(size=12, color="#E07A2C"),
    bgcolor="rgba(255,255,255,0.9)", bordercolor="#E07A2C", borderwidth=1, borderpad=4,
)

fig.update_layout(
    height=560,
    margin=dict(l=0, r=0, t=10, b=0),
    plot_bgcolor="white",
    xaxis=dict(gridcolor="#eee", showgrid=False, title_font=dict(size=14)),
    yaxis=dict(gridcolor="#eee", showgrid=True, title_font=dict(size=14)),
    font=dict(size=13),
)
st.plotly_chart(fig, use_container_width=True)

st.caption(
    "Source: FAOSTAT Food Balance Sheets, World Bank GDP per Capita. "
    f"Dashed line shows the overall trend across {year_df['Country'].nunique()} countries."
)

st.markdown("<div style='margin-top:36px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Key Takeaway
# ----------------------------------------------------------
st.markdown(
    f"""
    <div style="
        border-left: 4px solid #2A6F97;
        background-color: rgba(42,111,151,0.06);
        padding: 14px 20px;
        border-radius: 6px;
        font-size: 1.05rem;
        color: #262730;
        line-height: 1.6;
    ">
    Wealth and food security move together in broad strokes — but <b>{clean_name(top_over['Country'])}</b>
    shows strong food security can be achieved well below the GDP level that "should" produce it,
    while <b>{clean_name(top_under['Country'])}</b> shows high GDP alone offers no guarantee.
    The variables driving that gap — climate stress, agricultural capacity, and trade dependency —
    are what the rest of this dashboard investigates.
    </div>
    """,
    unsafe_allow_html=True
)