# -*- coding: utf-8 -*-
"""3_🌡️_Climate_Impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nw_mnJjIpAonWXM-6JP9P0kwq1G2di7R
"""

# ==========================================================
# Climate Impact (AQ4)
# ==========================================================
import streamlit as st
import numpy as np
import plotly.graph_objects as go

from utils import load_data, apply_sidebar_filters, clean_name

st.set_page_config(page_title="Climate Impact", page_icon="🌡️", layout="wide")

df = load_data()
filtered_df, year_range, selected_regions = apply_sidebar_filters(df)

st.title("🌡️ Climate Impact")
st.subheader("Who Stays Food Secure Even as the Planet Warms?")

latest_year = year_range[1]
year_df = filtered_df[filtered_df["Year"] == latest_year].dropna(
    subset=["Temperature_Change", "Calories_per_Capita"]
).copy()

st.caption(
    f"Cross-section for {latest_year} · {year_df['Country'].nunique()} countries in current filter"
)

temp_median = year_df["Temperature_Change"].median()
cal_median = year_df["Calories_per_Capita"].median()

def classify(row):
    if row["Temperature_Change"] >= temp_median and row["Calories_per_Capita"] >= cal_median:
        return "Resilient"
    elif row["Temperature_Change"] >= temp_median and row["Calories_per_Capita"] < cal_median:
        return "Vulnerable"
    elif row["Temperature_Change"] < temp_median and row["Calories_per_Capita"] >= cal_median:
        return "Comfortable"
    else:
        return "Watch List"

year_df["Quadrant"] = year_df.apply(classify, axis=1)

quadrant_colors = {
    "Resilient": "#2A6F97",
    "Vulnerable": "#E07A2C",
    "Comfortable": "#B0B0B0",
    "Watch List": "#5c5c5c",
}

n_resilient = (year_df["Quadrant"] == "Resilient").sum()
total = len(year_df)

# ----------------------------------------------------------
# KPI row
# ----------------------------------------------------------
col1, col2, col3 = st.columns([1, 1, 2])

with col1:
    st.markdown(
        '<div style="background-color:#FFFFFF; border-radius:10px; '
        'box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08); '
        'padding:16px 18px; min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
        '<div style="color:#666; font-size:0.95rem; font-weight:700; letter-spacing:0.03em; margin-bottom:8px;">RESILIENT COUNTRIES</div>'
        f'<div style="font-size:1.9rem; font-weight:800; color:#14213d;">{n_resilient}</div>'
        '</div>',
        unsafe_allow_html=True
    )

with col2:
    st.markdown(
        '<div style="background-color:#FFFFFF; border-radius:10px; '
        'box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08); '
        'padding:16px 18px; min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
        '<div style="color:#666; font-size:0.95rem; font-weight:700; letter-spacing:0.03em; margin-bottom:8px;">MEDIAN WARMING</div>'
        f'<div style="font-size:1.9rem; font-weight:800; color:#14213d;">+{temp_median:.2f}°C</div>'
        '</div>',
        unsafe_allow_html=True
    )

with col3:
    st.markdown(
        '<div style="min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
        '<div style="font-size:1.05rem; color:#333; line-height:1.6;">'
        "Countries are split into four groups by their <b>temperature anomaly</b> and "
        "<b>calorie supply</b>, relative to the median for each. The most interesting "
        "group isn't the richest or the warmest — it's the <b>Resilient</b> countries "
        "that stay food secure despite heavy warming."
        "</div>"
        "</div>",
        unsafe_allow_html=True
    )

st.markdown("<div style='margin-top:28px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Quadrant Scatter
# ----------------------------------------------------------
st.markdown("#### The Climate Resilience Map")
st.markdown(
    '<div style="font-size:1rem; color:#555; margin-bottom:8px; line-height:1.5;">'
    "Each point is one country, split into four groups by the median warming level "
    "and median calorie supply across all countries shown."
    "</div>",
    unsafe_allow_html=True
)

fig = go.Figure()

for quadrant, color in quadrant_colors.items():
    qdf = year_df[year_df["Quadrant"] == quadrant]
    fig.add_trace(go.Scatter(
        x=qdf["Temperature_Change"], y=qdf["Calories_per_Capita"],
        mode="markers", name=quadrant,
        marker=dict(size=8, color=color, opacity=0.75, line=dict(width=0.5, color="white")),
        text=qdf["Country"].apply(clean_name),
        hovertemplate="<b>%{text}</b><br>Temp anomaly: %{x:.2f}°C<br>Calories: %{y:.0f} kcal/day<extra></extra>",
    ))

fig.add_vline(x=temp_median, line_dash="dot", line_color="#ccc")
fig.add_hline(y=cal_median, line_dash="dot", line_color="#ccc")

x_range = year_df["Temperature_Change"].max() - year_df["Temperature_Change"].min()

fig.add_annotation(x=temp_median + x_range*0.28, y=year_df["Calories_per_Capita"].max(),
                    text="RESILIENT", showarrow=False, font=dict(size=12, color="#2A6F97"))
fig.add_annotation(x=temp_median + x_range*0.28, y=year_df["Calories_per_Capita"].min(),
                    text="VULNERABLE", showarrow=False, font=dict(size=12, color="#E07A2C"))
fig.add_annotation(x=temp_median - x_range*0.28, y=year_df["Calories_per_Capita"].max(),
                    text="COMFORTABLE", showarrow=False, font=dict(size=12, color="#999"))
fig.add_annotation(x=temp_median - x_range*0.28, y=year_df["Calories_per_Capita"].min(),
                    text="WATCH LIST", showarrow=False, font=dict(size=12, color="#5c5c5c"))

resilient_df = year_df[year_df["Quadrant"] == "Resilient"]
if not resilient_df.empty:
    standout = resilient_df.loc[resilient_df["Temperature_Change"].idxmax()]
    fig.add_annotation(
        x=standout["Temperature_Change"], y=standout["Calories_per_Capita"],
        text=f"<b>{clean_name(standout['Country'])}</b><br>most resilient in this view",
        showarrow=True, arrowhead=2, arrowcolor="#2A6F97", ax=40, ay=-40,
        font=dict(size=12, color="#2A6F97"),
        bgcolor="rgba(255,255,255,0.9)", bordercolor="#2A6F97", borderwidth=1, borderpad=4,
    )

fig.update_layout(
    height=560,
    margin=dict(l=0, r=0, t=10, b=0),
    plot_bgcolor="white",
    showlegend=False,
    xaxis=dict(title="Temperature Anomaly (°C)", gridcolor="#eee", showgrid=False),
    yaxis=dict(title="Calorie Supply (kcal/capita/day)", gridcolor="#eee"),
    font=dict(size=13),
)
st.plotly_chart(fig, use_container_width=True)

st.caption(
    "Source: FAOSTAT Food Balance Sheets & Temperature Change on Land. "
    "Quadrant lines mark the median temperature anomaly and median calorie supply "
    f"across {total} countries."
)

st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Quadrant Breakdown
# ----------------------------------------------------------
st.markdown("#### Group Breakdown")

quadrant_counts = year_df["Quadrant"].value_counts()
order = ["Resilient", "Vulnerable", "Comfortable", "Watch List"]

qcols = st.columns(4)
for col, qname in zip(qcols, order):
    count = int(quadrant_counts.get(qname, 0))
    pct = (count / total) * 100 if total else 0
    color = quadrant_colors[qname]
    with col:
        st.markdown(
            f'<div style="background-color:#FFFFFF; border-radius:10px; '
            f'box-shadow:0 4px 14px rgba(0,0,0,0.10), 0 1px 3px rgba(0,0,0,0.06); '
            f'border-top:3px solid {color}; padding:12px 16px; min-height:80px; '
            f'display:flex; flex-direction:column; justify-content:center;">'
            f'<div style="color:#666; font-size:0.85rem; font-weight:700; letter-spacing:0.03em;">{qname.upper()}</div>'
            f'<div style="font-size:1.4rem; font-weight:800; color:#14213d;">'
            f'{count} <span style="font-size:0.9rem; font-weight:600; color:#888;">({pct:.0f}%)</span></div>'
            f'</div>',
            unsafe_allow_html=True
        )

st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)

# ----------------------------------------------------------
# Key Takeaway
# ----------------------------------------------------------
pct_resilient = (n_resilient / total) * 100 if total else 0

st.markdown(
    f'<div style="border-left:4px solid #2A6F97; background-color:rgba(42,111,151,0.06); '
    f'padding:14px 20px; border-radius:6px; font-size:1.05rem; color:#262730; line-height:1.6;">'
    f"<b>{pct_resilient:.0f}%</b> of countries in this view sit in the \"Resilient\" group — "
    f"facing above-median warming but still maintaining above-median food supply. "
    f"Climate stress alone doesn't determine food security; what a country does about "
    f"it — through agriculture, trade, and infrastructure — matters just as much."
    f'</div>',
    unsafe_allow_html=True
)