# -*- coding: utf-8 -*-
"""4_🌾_Agriculture_&_Production.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRWIIBWQwjt-newApALr7M0MC1RR-VZI
"""

# ==========================================================
# Agriculture & Production (AQ7 / AQ8)
# ==========================================================
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from utils import load_data, apply_sidebar_filters, clean_name

st.set_page_config(page_title="Agriculture & Production", page_icon="🌾", layout="wide")

df = load_data()
filtered_df, year_range, selected_regions = apply_sidebar_filters(df)

st.title("🌾 Agriculture & Production")
st.subheader("Does Farming More Land or Growing More Food Actually Help?")

latest_year = year_range[1]
year_df = filtered_df[filtered_df["Year"] == latest_year].copy()

st.caption(
    f"Cross-section for {latest_year} · {year_df['Country'].nunique()} countries in current filter"
)

st.markdown("<div style='margin-top:8px;'></div>", unsafe_allow_html=True)

tab1, tab2 = st.tabs(["🌱 Agricultural Land Share", "🏭 Domestic Production"])

# ============================================================
# TAB 1 — Agricultural Land Share (AQ8)
# ============================================================
with tab1:
    land_df = year_df.dropna(subset=["Agricultural_Land_Percent", "Calories_per_Capita"]).copy()

    bins = [0, 20, 40, 60, 100]
    labels = ["<20%", "20–40%", "40–60%", "60%+"]
    land_df["Land_Tier"] = pd.cut(
        land_df["Agricultural_Land_Percent"], bins=bins, labels=labels, duplicates="drop"
    )

    tier_summary = (
        land_df.groupby("Land_Tier", observed=True)["Calories_per_Capita"]
        .agg(["mean", "count"])
        .reset_index()
    )

    corr_land = np.corrcoef(land_df["Agricultural_Land_Percent"], land_df["Calories_per_Capita"])[0, 1]
    overall_avg = land_df["Calories_per_Capita"].mean()

    best_idx = tier_summary["mean"].idxmax()
    worst_idx = tier_summary["mean"].idxmin()
    bar_colors = []
    for i in tier_summary.index:
        if i == best_idx:
            bar_colors.append("#2A6F97")
        elif i == worst_idx:
            bar_colors.append("#E07A2C")
        else:
            bar_colors.append("#B0B0B0")

    st.markdown("<div style='margin-top:16px;'></div>", unsafe_allow_html=True)
    col1, col2 = st.columns([1, 3])
    with col1:
        st.markdown(
            '<div style="background-color:#FFFFFF; border-radius:10px; '
            'box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08); '
            'padding:16px 18px; min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
            '<div style="color:#666; font-size:0.95rem; font-weight:700; letter-spacing:0.03em; margin-bottom:8px;">LAND–FOOD CORRELATION</div>'
            f'<div style="font-size:1.9rem; font-weight:800; color:#14213d;">{corr_land:.2f}</div>'
            '</div>',
            unsafe_allow_html=True
        )
    with col2:
        st.markdown(
            '<div style="min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
            '<div style="font-size:1.05rem; color:#333; line-height:1.6;">'
            f"A correlation of <b>{corr_land:.2f}</b> — essentially zero — shows agricultural land "
            "share has almost no direct relationship with calorie supply. Farming more land doesn't "
            "reliably translate into more food on the table."
            "</div></div>",
            unsafe_allow_html=True
        )

    st.markdown("<div style='margin-top:24px;'></div>", unsafe_allow_html=True)
    st.markdown("#### More Farmland Doesn't Mean More Food")
    st.markdown(
        '<div style="font-size:1rem; color:#555; margin-bottom:8px; line-height:1.5;">'
        "Countries are grouped by the share of their land used for agriculture. The dashed line "
        "marks the overall average across all countries shown; "
        '<span style="color:#2A6F97; font-weight:600;">blue</span> highlights the best-performing tier, '
        '<span style="color:#E07A2C; font-weight:600;">amber</span> the weakest.'
        "</div>",
        unsafe_allow_html=True
    )

    bar_labels = [
        f"{int(row['mean'])}<br><span style='font-size:11px; color:#888'>{row['count']} countries</span>"
        for _, row in tier_summary.iterrows()
    ]

    y_max = tier_summary["mean"].max()

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=tier_summary["Land_Tier"].astype(str), y=tier_summary["mean"],
        marker_color=bar_colors,
        text=bar_labels,
        textposition="outside",
        hovertemplate="Tier: %{x}<br>Avg calories: %{y:.0f} kcal/day<br>Countries: %{customdata}<extra></extra>",
        customdata=tier_summary["count"],
    ))
    fig.add_hline(y=overall_avg, line_dash="dot", line_color="#888")
    fig.add_annotation(
        xref="paper", yref="paper",
        x=0.99, y=1.05,
        text=f"⋯ Overall average: {overall_avg:.0f} kcal/day",
        showarrow=False, xanchor="right", yanchor="bottom",
        font=dict(size=11, color="#888"),
    )
    fig.update_layout(
        height=480,
        margin=dict(l=0, r=0, t=55, b=0),
        plot_bgcolor="white",
        xaxis=dict(title="Agricultural Land Share of Total Land", showgrid=False),
        yaxis=dict(
            title="Avg. Calorie Supply (kcal/capita/day)",
            gridcolor="#eee",
            range=[0, y_max * 1.22],
        ),
        font=dict(size=13),
    )
    st.plotly_chart(fig, use_container_width=True)
    st.caption(
        f"Source: World Bank Agricultural Land (% of land area), FAOSTAT Food Balance Sheets. "
        f"{land_df['Country'].nunique()} countries in current filter. Tiers with fewer countries "
        f"carry more uncertainty in their average."
    )

    st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)
    st.markdown(
        '<div style="border-left:4px solid #2A6F97; background-color:rgba(42,111,151,0.06); '
        'padding:14px 20px; border-radius:6px; font-size:1.05rem; color:#262730; line-height:1.6;">'
        "There's no clean, rising relationship between land share and food supply — the 40–60% "
        "tier has the highest average, not the countries farming the most land, and the 60%+ tier "
        "sits close to the overall average rather than clearly above it. Land quantity alone isn't "
        "the driver; how that land is used, and what else supports the food system, matters more."
        "</div>",
        unsafe_allow_html=True
    )

# ============================================================
# TAB 2 — Domestic Production (AQ7)
# ============================================================
with tab2:
    prod_df = year_df.dropna(
        subset=["Production_Total", "Calories_per_Capita", "Population"]
    ).copy()
    prod_df = prod_df[prod_df["Production_Total"] > 0].copy()

    log_prod = np.log10(prod_df["Production_Total"])
    corr_prod = np.corrcoef(log_prod, prod_df["Calories_per_Capita"])[0, 1]

    st.markdown("<div style='margin-top:16px;'></div>", unsafe_allow_html=True)
    col1, col2 = st.columns([1, 3])
    with col1:
        st.markdown(
            '<div style="background-color:#FFFFFF; border-radius:10px; '
            'box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08); '
            'padding:16px 18px; min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
            '<div style="color:#666; font-size:0.95rem; font-weight:700; letter-spacing:0.03em; margin-bottom:8px;">PRODUCTION–FOOD CORRELATION</div>'
            f'<div style="font-size:1.9rem; font-weight:800; color:#14213d;">{corr_prod:.2f}</div>'
            '</div>',
            unsafe_allow_html=True
        )
    with col2:
        st.markdown(
            '<div style="min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
            '<div style="font-size:1.05rem; color:#333; line-height:1.6;">'
            f"A correlation of <b>{corr_prod:.2f}</b> shows domestic production volume has a weak "
            "direct link to calorie availability at the national level — production feeds trade "
            "and exports too, not just domestic supply."
            "</div></div>",
            unsafe_allow_html=True
        )

    st.markdown("<div style='margin-top:24px;'></div>", unsafe_allow_html=True)
    st.markdown("#### High Output, Low Payoff: The Production Paradox")
    st.markdown(
        '<div style="font-size:1rem; color:#555; margin-bottom:8px; line-height:1.5;">'
        "Each bubble is one country, sized by population — so a large bubble in a weak position "
        "means many people are affected, not just a small nation's statistic. Production is shown "
        "on a logarithmic scale since output volumes vary enormously by country size."
        "</div>",
        unsafe_allow_html=True
    )

    slope, intercept = np.polyfit(log_prod, prod_df["Calories_per_Capita"], 1)
    trend_x = np.linspace(log_prod.min(), log_prod.max(), 100)
    trend_y = slope * trend_x + intercept

    prod_df["predicted"] = slope * log_prod + intercept
    prod_df["residual"] = prod_df["Calories_per_Capita"] - prod_df["predicted"]

    volume_threshold = prod_df["Production_Total"].quantile(0.75)
    big_producers = prod_df[prod_df["Production_Total"] >= volume_threshold]
    paradox_country = big_producers.loc[big_producers["Calories_per_Capita"].idxmin()]
    overachiever = prod_df.loc[prod_df["residual"].idxmax()]

    fig2 = px.scatter(
        prod_df, x="Production_Total", y="Calories_per_Capita",
        size="Population", size_max=45,
        hover_name="Country", log_x=True,
        color_discrete_sequence=["#B0B0B0"],
        labels={
            "Production_Total": "Domestic Production (tonnes, log scale)",
            "Calories_per_Capita": "Calorie Supply (kcal/capita/day)",
        },
        opacity=0.5,
    )
    fig2.update_traces(marker=dict(line=dict(width=0.5, color="white")))
    fig2.add_trace(go.Scatter(
        x=10 ** trend_x, y=trend_y, mode="lines",
        line=dict(color="#888", width=2, dash="dash"), showlegend=False, hoverinfo="skip",
    ))

    fig2.add_trace(go.Scatter(
        x=[paradox_country["Production_Total"]], y=[paradox_country["Calories_per_Capita"]],
        mode="markers", marker=dict(size=15, color="#E07A2C", line=dict(width=2, color="white")),
        showlegend=False, hoverinfo="skip",
    ))
    fig2.add_annotation(
        x=np.log10(paradox_country["Production_Total"]), y=paradox_country["Calories_per_Capita"],
        text=f"<b>{clean_name(paradox_country['Country'])}</b><br>major producer, low calorie supply",
        showarrow=True, arrowhead=2, arrowcolor="#E07A2C", ax=-60, ay=40,
        font=dict(size=12, color="#E07A2C"),
        bgcolor="rgba(255,255,255,0.9)", bordercolor="#E07A2C", borderwidth=1, borderpad=4,
    )

    fig2.add_trace(go.Scatter(
        x=[overachiever["Production_Total"]], y=[overachiever["Calories_per_Capita"]],
        mode="markers", marker=dict(size=15, color="#2A6F97", line=dict(width=2, color="white")),
        showlegend=False, hoverinfo="skip",
    ))
    fig2.add_annotation(
        x=np.log10(overachiever["Production_Total"]), y=overachiever["Calories_per_Capita"],
        text=f"<b>{clean_name(overachiever['Country'])}</b><br>modest output, strong food supply",
        showarrow=True, arrowhead=2, arrowcolor="#2A6F97", ax=50, ay=-40,
        font=dict(size=12, color="#2A6F97"),
        bgcolor="rgba(255,255,255,0.9)", bordercolor="#2A6F97", borderwidth=1, borderpad=4,
    )

    fig2.update_layout(
        height=520, margin=dict(l=0, r=0, t=10, b=0), plot_bgcolor="white",
        xaxis=dict(gridcolor="#eee", showgrid=False),
        yaxis=dict(gridcolor="#eee", showgrid=True),
        font=dict(size=13),
    )
    st.plotly_chart(fig2, use_container_width=True)
    st.caption(
        "Source: FAOSTAT Production & Food Balance Sheets, World Bank Population. "
        f"{prod_df['Country'].nunique()} countries in current filter. Bubble size reflects population."
    )

    st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)
    st.markdown(
        f'<div style="border-left:4px solid #2A6F97; background-color:rgba(42,111,151,0.06); '
        f'padding:14px 20px; border-radius:6px; font-size:1.05rem; color:#262730; line-height:1.6;">'
        f"Producing more food domestically doesn't automatically mean a country's own population "
        f"eats better. <b>{clean_name(paradox_country['Country'])}</b> is a major producer with "
        f"comparatively low calorie supply, while <b>{clean_name(overachiever['Country'])}</b> "
        f"achieves strong food supply on modest production — a large share of what's produced "
        f"can be exported rather than consumed at home."
        f'</div>',
        unsafe_allow_html=True
    )