# -*- coding: utf-8 -*-
"""6_🏆_Rankings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uLrU8XNvhYs4tVxUtfaLT6rlERQvyRs
"""

# ==========================================================
# Rankings (AQ12) — Composite Resilience Index
# ==========================================================
import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from utils import load_data, apply_sidebar_filters, clean_name

st.set_page_config(page_title="Rankings", page_icon="🏆", layout="wide")

df = load_data()
filtered_df, year_range, selected_regions = apply_sidebar_filters(df)

st.title("🏆 Rankings")
st.subheader("Who's Actually Winning the Food Security Race?")

st.markdown(
    '<div style="font-size:1.05rem; color:#333; line-height:1.6; max-width:900px; margin-bottom:16px;">'
    "Every prior tab looked at one factor at a time. This ranking combines four into a single "
    "<b>Resilience Score</b>: food supply, climate stress, how well a country outperforms its GDP "
    "level, and how self-sufficient it is on trade — the same four stories this dashboard has been "
    "telling, now merged into one number per country."
    "</div>",
    unsafe_allow_html=True
)

latest_year = year_range[1]
year_df = filtered_df[filtered_df["Year"] == latest_year].dropna(
    subset=["Calories_per_Capita", "Temperature_Change", "GDP_per_Capita",
            "Imports_Total", "Domestic_Supply_Total"]
).copy()

def robust_zscore(s, clip=3):
    z = (s - s.mean()) / s.std()
    return z.clip(-clip, clip)

z_calories = robust_zscore(year_df["Calories_per_Capita"])
z_temp = -robust_zscore(year_df["Temperature_Change"])

log_gdp = np.log10(year_df["GDP_per_Capita"])
slope, intercept = np.polyfit(log_gdp, year_df["Calories_per_Capita"], 1)
predicted = slope * log_gdp + intercept
residual = year_df["Calories_per_Capita"] - predicted
z_residual = robust_zscore(residual)

year_df["Import_Dependency"] = year_df["Imports_Total"] / year_df["Domestic_Supply_Total"].replace(0, np.nan)
import_dep_filled = year_df["Import_Dependency"].fillna(year_df["Import_Dependency"].median())
z_trade = -robust_zscore(import_dep_filled)

year_df["Resilience_Score"] = (z_calories + z_temp + z_residual + z_trade) / 4

score_min, score_max = year_df["Resilience_Score"].min(), year_df["Resilience_Score"].max()
year_df["Resilience_Index"] = (
    (year_df["Resilience_Score"] - score_min) / (score_max - score_min) * 100
)

top_country = year_df.loc[year_df["Resilience_Index"].idxmax()]
bottom_country = year_df.loc[year_df["Resilience_Index"].idxmin()]
median_score = year_df["Resilience_Index"].median()

col1, col2, col3 = st.columns(3)
with col1:
    st.markdown(
        '<div style="background-color:#FFFFFF; border-radius:10px; '
        'box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08); '
        'padding:16px 18px; min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
        '<div style="color:#666; font-size:0.9rem; font-weight:700; letter-spacing:0.03em; margin-bottom:8px;">TOP-RANKED</div>'
        f'<div style="font-size:1.5rem; font-weight:800; color:#14213d;">{clean_name(top_country["Country"])}</div>'
        f'<div style="font-size:0.85rem; color:#2A6F97; font-weight:600;">Score: {top_country["Resilience_Index"]:.0f}/100</div>'
        '</div>',
        unsafe_allow_html=True
    )
with col2:
    st.markdown(
        '<div style="background-color:#FFFFFF; border-radius:10px; '
        'box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08); '
        'padding:16px 18px; min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
        '<div style="color:#666; font-size:0.9rem; font-weight:700; letter-spacing:0.03em; margin-bottom:8px;">LOWEST-RANKED</div>'
        f'<div style="font-size:1.5rem; font-weight:800; color:#14213d;">{clean_name(bottom_country["Country"])}</div>'
        f'<div style="font-size:0.85rem; color:#E07A2C; font-weight:600;">Score: {bottom_country["Resilience_Index"]:.0f}/100</div>'
        '</div>',
        unsafe_allow_html=True
    )
with col3:
    st.markdown(
        '<div style="background-color:#FFFFFF; border-radius:10px; '
        'box-shadow:0 4px 14px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.08); '
        'padding:16px 18px; min-height:95px; display:flex; flex-direction:column; justify-content:center;">'
        '<div style="color:#666; font-size:0.9rem; font-weight:700; letter-spacing:0.03em; margin-bottom:8px;">MEDIAN SCORE</div>'
        f'<div style="font-size:1.9rem; font-weight:800; color:#14213d;">{median_score:.0f}/100</div>'
        '</div>',
        unsafe_allow_html=True
    )

st.markdown(
    "<div style='margin-top:12px; font-size:0.85rem; color:#888;'>"
    "Score combines: food supply, climate stress (inverted), GDP-adjusted performance, and trade "
    "self-sufficiency — each weighted equally, rescaled to 0–100. Extreme outliers are capped so "
    "one unusual country can't distort the scale for everyone else."
    "</div>", unsafe_allow_html=True
)

st.markdown("<div style='margin-top:40px;'></div>", unsafe_allow_html=True)

st.markdown("#### The Leaderboard")

scope = st.radio(
    "Scope:", ["Global", "Within a single region"], horizontal=True, label_visibility="collapsed"
)

if scope == "Within a single region":
    region_choice = st.selectbox("Region:", sorted(year_df["Region"].dropna().unique()))
    scope_df = year_df[year_df["Region"] == region_choice]
    scope_label = region_choice
else:
    scope_df = year_df
    scope_label = "the world"

n_show = min(10, len(scope_df) // 2) if len(scope_df) >= 4 else len(scope_df)

top_n = scope_df.nlargest(n_show, "Resilience_Index").sort_values("Resilience_Index")
bottom_n = scope_df.nsmallest(n_show, "Resilience_Index").sort_values("Resilience_Index", ascending=False)

top_n = top_n.copy(); top_n["Rank_Group"] = "Top"
bottom_n = bottom_n.copy(); bottom_n["Rank_Group"] = "Bottom"

bottom_n["Display_Name"] = bottom_n["Country"].apply(clean_name)
top_n["Display_Name"] = top_n["Country"].apply(clean_name)

spacer = pd.DataFrame([{"Display_Name": "", "Resilience_Index": np.nan, "Rank_Group": "Spacer"}])
leaderboard = pd.concat([bottom_n, spacer, top_n], ignore_index=True)

y_order = leaderboard["Display_Name"].tolist()

fig = go.Figure()

plot_df = leaderboard.dropna(subset=["Resilience_Index"])

for _, row in plot_df.iterrows():
    color = "#2A6F97" if row["Rank_Group"] == "Top" else "#E07A2C"
    fig.add_shape(
        type="line", x0=0, x1=row["Resilience_Index"],
        y0=row["Display_Name"], y1=row["Display_Name"],
        line=dict(color=color, width=2), opacity=0.45,
    )

colors = ["#2A6F97" if g == "Top" else "#E07A2C" for g in plot_df["Rank_Group"]]

fig.add_trace(go.Scatter(
    x=plot_df["Resilience_Index"], y=plot_df["Display_Name"],
    mode="markers+text",
    marker=dict(size=12, color=colors, line=dict(width=1, color="white")),
    text=plot_df["Resilience_Index"].round(0).astype(int).astype(str),
    textposition="middle right",
    textfont=dict(size=11, color="#333"),
    hovertemplate="<b>%{y}</b><br>Score: %{x:.0f}/100<extra></extra>",
    showlegend=False,
))

fig.add_vline(x=median_score, line_dash="dot", line_color="#ccc")

# Fixed to the plot's top/bottom edges — robust no matter how many rows exist
fig.add_annotation(
    xref="paper", yref="paper", x=0.02, y=0.98,
    text=f"▲ Top {n_show}", showarrow=False,
    font=dict(size=12, color="#2A6F97", family="Arial Black"),
    xanchor="left", yanchor="top",
)
fig.add_annotation(
    xref="paper", yref="paper", x=0.02, y=0.02,
    text=f"▼ Bottom {n_show}", showarrow=False,
    font=dict(size=12, color="#E07A2C", family="Arial Black"),
    xanchor="left", yanchor="bottom",
)

fig.update_layout(
    height=max(480, 34 * len(plot_df) + 60),
    margin=dict(l=10, r=60, t=50, b=10),
    plot_bgcolor="white",
    xaxis=dict(title="Resilience Index (0–100)", gridcolor="#eee", range=[0, 115]),
    yaxis=dict(title="", gridcolor="white", categoryorder="array", categoryarray=y_order),
    font=dict(size=13),
)
st.plotly_chart(fig, use_container_width=True)
st.caption(
    f"Showing the top and bottom {n_show} countries in {scope_label} by Resilience Index. "
    "Blue marks the top group, amber the bottom group. The dotted line marks the median score. "
    "Because scores are rescaled to a 0–100 range, the single lowest country will always show as "
    "0 and the highest as 100 — this reflects relative standing among the countries shown, not an "
    "absolute measure of resilience. "
    "Source: FAOSTAT & World Bank, composite index calculated from this dashboard's underlying data."
)

st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)


top_gdp_rank = int(year_df["GDP_per_Capita"].rank(ascending=False).loc[top_country.name])

if top_gdp_rank <= 3:
    synthesis_text = (
        f"<b>{clean_name(top_country['Country'])}</b> tops this ranking, and it's also near the top "
        f"on GDP per capita (globally ranked <b>#{top_gdp_rank}</b>) — here, economic strength and "
        f"resilience genuinely move together. But that's not guaranteed: several countries much "
        f"lower on this list have comparable or higher GDP, which is exactly why climate exposure "
        f"and trade self-sufficiency still matter as separate factors, not just GDP alone."
    )
else:
    synthesis_text = (
        f"<b>{clean_name(top_country['Country'])}</b> tops this ranking — and it isn't the country "
        f"with the highest GDP (it ranks <b>#{top_gdp_rank}</b> globally on GDP per capita). "
        f"That's the thesis of this entire dashboard in one number: resilience comes from balancing "
        f"economic strength, climate exposure, and self-sufficiency — not from wealth alone."
    )

st.markdown(
    f'<div style="border-left:4px solid #2A6F97; background-color:rgba(42,111,151,0.06); '
    f'padding:14px 20px; border-radius:6px; font-size:1.05rem; color:#262730; line-height:1.6;">'
    f"{synthesis_text}"
    f'</div>',
    unsafe_allow_html=True
)