# -*- coding: utf-8 -*-
"""7_ℹ️_About.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-PdWMesrFj0IvDQIAI99ndlVLXnaDN9
"""

# ==========================================================
# About
# ==========================================================
import streamlit as st


st.set_page_config(page_title="About", page_icon="ℹ️", layout="wide")


st.title("ℹ️ About This Dashboard")
st.subheader("The Data, the Method, and the Question Behind It")


st.markdown(
    '<div style="max-width:900px;">'
    '<div style="border-left:4px solid #2A6F97; padding:10px 20px; margin:16px 0 24px 0; '
    'font-size:1.2rem; font-style:italic; color:#2A6F97;">'
    "Economic growth is often treated as the whole story of food security. This dashboard was built "
    "to test that assumption — and to show where climate stress, agriculture, and trade tell a "
    "different, sometimes contradicting, story."
    "</div></div>",
    unsafe_allow_html=True
)


st.markdown("<div style='margin-top:8px;'></div>", unsafe_allow_html=True)


# ----------------------------------------------------------
# What this dashboard covers
# ----------------------------------------------------------
st.markdown("#### What's Inside")
st.markdown(
    '<div style="font-size:1.05rem; color:#333; line-height:1.7; max-width:900px; margin-bottom:20px;">'
    "Seven views, each answering a different piece of the same question:"
    "</div>",
    unsafe_allow_html=True
)


sections = [
    ("📊", "Executive Overview", "A global snapshot — KPIs, a world map, and the three biggest headline findings."),
    ("🌍", "Global Trends", "Has food supply kept pace with rising global temperatures since 2010?"),
    ("💰", "Economy & Food", "Does GDP per capita reliably predict food availability?"),
    ("🌡️", "Climate Impact", "Which countries stay food secure despite heavy climate stress?"),
    ("🌾", "Agriculture & Production", "Does farming more land, or producing more food, actually help?"),
    ("🔎", "Country Explorer", "A deep dive into any single country's economy, climate, and trade story, benchmarked against its region."),
    ("🏆", "Rankings", "A composite Resilience Index combining food supply, climate stress, GDP performance, and trade self-sufficiency."),
]


for icon, name, desc in sections:
    st.markdown(
        f'<div style="display:flex; align-items:flex-start; gap:12px; margin-bottom:14px; max-width:900px;">'
        f'<div style="font-size:1.3rem;">{icon}</div>'
        f'<div><span style="font-weight:700; color:#14213d;">{name}</span>'
        f'<span style="color:#555;"> — {desc}</span></div>'
        f'</div>',
        unsafe_allow_html=True
    )


st.markdown("<div style='margin-top:28px;'></div>", unsafe_allow_html=True)


# ----------------------------------------------------------
# Data sources
# ----------------------------------------------------------
st.markdown("#### Data Sources")


col1, col2 = st.columns(2)
with col1:
    st.markdown(
        '<div style="background-color:#FFFFFF; border-radius:10px; '
        'box-shadow:0 4px 14px rgba(0,0,0,0.10), 0 1px 3px rgba(0,0,0,0.06); '
        'padding:18px 20px; min-height:160px;">'
        '<div style="font-weight:700; color:#14213d; font-size:1.05rem; margin-bottom:8px;">FAOSTAT</div>'
        '<ul style="color:#444; font-size:0.95rem; line-height:1.6; margin:0; padding-left:18px;">'
        "<li>Food Balance Sheets — calorie and food quantity supply per capita</li>"
        "<li>Temperature Change on Land — annual temperature anomaly by country</li>"
        "</ul>"
        '<div style="color:#888; font-size:0.85rem; margin-top:10px;">Source: Food and Agriculture Organization of the United Nations</div>'
        '</div>',
        unsafe_allow_html=True
    )
with col2:
    st.markdown(
        '<div style="background-color:#FFFFFF; border-radius:10px; '
        'box-shadow:0 4px 14px rgba(0,0,0,0.10), 0 1px 3px rgba(0,0,0,0.06); '
        'padding:18px 20px; min-height:160px;">'
        '<div style="font-weight:700; color:#14213d; font-size:1.05rem; margin-bottom:8px;">World Bank</div>'
        '<ul style="color:#444; font-size:0.95rem; line-height:1.6; margin:0; padding-left:18px;">'
        "<li>GDP per Capita (current US$)</li>"
        "<li>Population, total</li>"
        "<li>Agricultural Land (% of land area)</li>"
        "</ul>"
        '<div style="color:#888; font-size:0.85rem; margin-top:10px;">Source: World Bank Open Data</div>'
        '</div>',
        unsafe_allow_html=True
    )


st.markdown(
    '<div style="font-size:0.95rem; color:#555; margin-top:14px; max-width:900px; line-height:1.6;">'
    "Five datasets, two providers, merged into a single panel covering <b>178 countries from "
    "2010 to 2023</b>. Regional aggregates (e.g. \"World,\" \"Africa,\" income-group totals) were "
    "identified and excluded before merging, to prevent them from being counted as if they were "
    "individual countries."
    "</div>",
    unsafe_allow_html=True
)


st.markdown("<div style='margin-top:28px;'></div>", unsafe_allow_html=True)


# ----------------------------------------------------------
# Methodology notes — corrected to match actual chart logic
# ----------------------------------------------------------
st.markdown("#### A Few Notes on Method")
st.markdown(
    '<div style="font-size:1rem; color:#333; line-height:1.7; max-width:900px;">'
    "<ul style='padding-left:20px;'>"
    "<li style='margin-bottom:10px;'><b>Log scales on GDP and production charts</b> — these values span "
    "an enormous range across countries (hundreds of dollars to over a hundred thousand), so a "
    "logarithmic scale keeps small and large countries both readable on the same chart.</li>"
    "<li style='margin-bottom:10px;'><b>The Climate Impact quadrant uses the median</b>, calculated "
    "live from whichever countries and years are currently selected in the sidebar filters — not a "
    "fixed threshold, so the split stays meaningful as filters change. The Agriculture & Production "
    "land tiers, by contrast, use fixed percentage bands (e.g. under 20%, 20–40%), since land share "
    "is a natural, fixed-scale measure.</li>"
    "<li style='margin-bottom:10px;'><b>The Resilience Index (Rankings tab)</b> combines four factors "
    "— food supply, climate stress, GDP-adjusted performance, and trade self-sufficiency — as equally "
    "weighted z-scores, clipped to prevent a single extreme country from distorting the scale for "
    "everyone else, then rescaled to 0–100.</li>"
    "<li style='margin-bottom:10px;'><b>Small groups carry more uncertainty.</b> Where a tier or region "
    "contains only a handful of countries, that's noted directly on the chart — averages from very "
    "few countries are less reliable than averages from many.</li>"
    "</ul>"
    "</div>",
    unsafe_allow_html=True
)


st.markdown("<div style='margin-top:28px;'></div>", unsafe_allow_html=True)


# ----------------------------------------------------------
# Design system
# ----------------------------------------------------------
st.markdown("#### Design Choices")
st.markdown(
    '<div style="font-size:1rem; color:#333; line-height:1.7; max-width:900px;">'
    "All charts use a colorblind-safe palette (muted blue, amber, and grey) so that findings remain "
    "readable regardless of color vision. Charts favor direct labels over legends wherever there are "
    "only a few series to identify, and every figure states its takeaway in the heading rather than a "
    "neutral description."
    "</div>",
    unsafe_allow_html=True
)


st.markdown("<div style='margin-top:32px;'></div>", unsafe_allow_html=True)


# ----------------------------------------------------------
# Project Information (REVISED)
# ----------------------------------------------------------

st.markdown("#### Project Information")

project_info_html = """
<div style="
    background-color:#FFFFFF;
    border:1px solid #E5E7EB;
    border-radius:8px;
    padding:18px 20px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size:0.95rem;
    color:#1F2937;
    line-height:1.55;
    max-width:900px;
">
    <table style="width:100%; border-collapse:collapse;">
        <tr>
            <td style="width:150px; vertical-align:top; padding:6px 0;">
                <b>Author</b>
            </td>
            <td style="padding:6px 0;">
                Anupriya Segar
            </td>
        </tr>
        <tr>
            <td style="vertical-align:top; padding:6px 0;">
                <b>Project</b>
            </td>
            <td style="padding:6px 0;">
                Interactive dashboard exploring the relationships between
                <b>economic growth</b>, <b>climate resilience</b>,
                <b>agriculture</b>, and <b>food security</b>.
            </td>
        </tr>
        <tr>
            <td style="vertical-align:top; padding:6px 0;">
                <b>Repository</b>
            </td>
            <td style="padding:6px 0;">
                <a href="https://github.com/Anupriya-Segar/beyond-economic-growth"
                   target="_blank"
                   style="color:#2563EB; text-decoration:none; font-weight:500;">
                    github.com/Anupriya-Segar/beyond-economic-growth
                </a>
            </td>
        </tr>
    </table>
</div>
"""

st.html(project_info_html)

st.markdown("<div style='height:22px;'></div>", unsafe_allow_html=True)


# ----------------------------------------------------------
# Official Data Sources (REVISED)
# ----------------------------------------------------------

st.markdown("#### Official Data Sources")

data_sources_html = """
<div style="
    background-color:#FFFFFF;
    border:1px solid #E5E7EB;
    border-radius:8px;
    padding:18px 20px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size:0.95rem;
    color:#1F2937;
    line-height:1.7;
    max-width:900px;
">
    <div style="font-weight:600; color:#111827; margin-bottom:10px; font-size:1.02rem;">
        Primary data providers
    </div>

    <ul style="margin:0 0 12px 0; padding-left:18px; color:#374151;">
        <li style="margin-bottom:8px;">
            <a href="https://www.fao.org/faostat/en/#data/FBS" target="_blank"
               style="color:#2563EB; text-decoration:none;">
                FAOSTAT – Food Balance Sheets
            </a>
        </li>
        <li style="margin-bottom:8px;">
            <a href="https://www.fao.org/faostat/en/#data/ET" target="_blank"
               style="color:#2563EB; text-decoration:none;">
                FAOSTAT – Temperature Change on Land
            </a>
        </li>
        <li style="margin-bottom:8px;">
            <a href="https://data.worldbank.org/indicator/NY.GDP.PCAP.CD" target="_blank"
               style="color:#2563EB; text-decoration:none;">
                World Bank – GDP per Capita
            </a>
        </li>
        <li style="margin-bottom:8px;">
            <a href="https://data.worldbank.org/indicator/SP.POP.TOTL" target="_blank"
               style="color:#2563EB; text-decoration:none;">
                World Bank – Population
            </a>
        </li>
        <li style="margin-bottom:8px;">
            <a href="https://data.worldbank.org/indicator/AG.LND.AGRI.ZS" target="_blank"
               style="color:#2563EB; text-decoration:none;">
                World Bank – Agricultural Land (%)
            </a>
        </li>
    </ul>

</div>
"""

st.html(data_sources_html)